### ISSUE TITLE
SI1145 showing really high UV index

### ISSUE THREAD

**Issue by szerwi** [adafruit/Adafruit_SI1145_Library#10]
My SI1145 sensor is showing really high UV index. It shows 5-6, whereas weather forecasts show 2-3. Is my sensor damaged, or do I need to change something in the code? I have this sensor, from China.
![si1145](https://user-images.githubusercontent.com/19311511/46914464-602acc00-cf9e-11e8-9645-3741956bef66.PNG)

**Comment by ladyada** [comment]
hiya, please contact the seller for a new one if you think its broken. thank u!
