### ISSUE TITLE
Si1145 does not work when changing I2C frequency

### ISSUE THREAD

**Issue by szerwi** [adafruit/Adafruit_SI1145_Library#9]
Hi,

The sensor is not working when I change I2C frequency from default 100kHz to 10kHz by Wire.setClock(10000); command. What is wrong?

**Comment by ladyada** [comment]
this chip has an unusual i2c implementation, it doesnt suprise me it doesn't work at non-standard frequencies. its nothing that can be fixed, please use 100K :)
